# Site settings
title: Grokking Engineering
tag_text: Grokking Engineering
description: Grokking Engineering is a community of strong developers in HCMC.

# Build settings
markdown: kramdown

exclude: ["README.md"]
